# Indicate to Travis CI that we need root permissions
sudo: required

# Tell Travis which services we need
services:
  - docker

# Steps to launch before running the tests
before_install:
  - docker build -t driesraman/test-docker-react -f Dockerfile.dev .

# Commands needed to run the testsuite
script:
  - docker run driesraman/test-docker-react npm run test -- --coverage

# indicate what to do once the "script" section passes all steps (= tests in our case)
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "test-docker-react"
  env: "TestDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-692078057127"
  bucket_path: "test-docker-react"
  on:
      branch: master
  access_key_id: "$AWS_ACCESS_KEY" # Configured in the Travis CI project configuration
  secret_access_key: 
    secure: "$AWS_SECRET_KEY" # Configured in the Travis CI project configuration